function filtered_signal = bandpass(signal, freq_range, Fs)
bpFilt = designfilt('bandpassiir', ...
                    'FilterOrder', 4, ...
                    'HalfPowerFrequency1', freq_range(1), ...
                    'HalfPowerFrequency2', freq_range(2), ...
                    'SampleRate', Fs);

filtered_signal = filtfilt(bpFilt, signal);
end
